name: Decadence
favicon: null
layout_spectrum: 1
typography_spectrum: 0.19525
title: Guilt-free self-indulgence
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d0d0d'
    - '#878787'
    - '#656565'
    - '#cacaca'
    - '#f2f2f2'
  brandStrength: 0.8125
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
