name: Decadence
favicon: null
layout_spectrum: 0.25177
typography_spectrum: 0
title: Guilt-free self-indulgence
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d0d0d'
    - '#878787'
    - '#656565'
    - '#cacaca'
    - '#f2f2f2'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.8175826510414481
  rhythmicContrast: 0.5
purpose: []
