name: Decadence
favicon: null
layout_spectrum: 0.14398771640844643
typography_spectrum: 0.0975775676779449
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.13111349008977413
  lightness: 0.8232362805865705
  saturation: 0.8175826510414481
  rhythmicContrast: 0.215091563295573
purpose: []
